<?php 
/* Fallback in case other extensions are not installed */
if ( !Mage::getStoreConfig('opengraphtags/conf/active') && !Mage::getStoreConfig('socialshare/general/enabled') ): 
?>
	<!-- BEGIN Facebook Social Init Default -->
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<!-- END Facebook Social Init Default -->
<?php endif; ?>
<!-- SocialShare - Facebook Comments -->
<div class="fbCommentsContainer" style="min-height:160px;">
	<div class="fb-comments" data-href="<?php echo $this->helper('core/url')->getCurrentUrl();?>" data-num-posts="<?php echo Mage::getStoreConfig('facebookcomments/conf/posts'); ?>" data-width="<?php echo Mage::getStoreConfig('facebookcomments/conf/width'); ?>" data-colorscheme="<?php echo Mage::getStoreConfig('facebookcomments/conf/colorscheme'); ?>"></div>
</div>
<!-- SocialShare - Facebook Comments END -->

