<?php
	// General Settings of the slide show
	$slideLink = Mage::getStoreConfig('layerslider/settings/slidelinkurl');
	$autoPlay = Mage::getStoreConfig('layerslider/settings/autoplay');
	$autoPlayInterval = Mage::getStoreConfig('layerslider/settings/autoplayinterval');
	$pauseOnHover = Mage::getStoreConfig('layerslider/settings/pauseonhover');
	$arrowKeyNav = Mage::getStoreConfig('layerslider/settings/arrowkeynav');
	$slideDuration = Mage::getStoreConfig('layerslider/settings/slideduration');
	$minDragOffset = Mage::getStoreConfig('layerslider/settings/mindragoffset');
	$playOrientation = Mage::getStoreConfig('layerslider/settings/playorientation');
	$dragOrientation = Mage::getStoreConfig('layerslider/settings/dragorientation');
	$arrowNavigation = Mage::getStoreConfig('layerslider/settings/arrownavigation');
	$arrowAutoCenter = Mage::getStoreConfig('layerslider/settings/arrowautocenter');
	$bulletNavigation = Mage::getStoreConfig('layerslider/settings/bulletnavigation');
	$bulletAutoCenter = Mage::getStoreConfig('layerslider/settings/bulletautocenter');
	
	//Slide Settings of the slide
	$slideEffects = Mage::getStoreConfig('layerslider/slidesettings/slideeffects');
	$autoHeight = Mage::getStoreConfig('layerslider/slidesettings/autoheight');
	$slideHeight = Mage::getStoreConfig('layerslider/slidesettings/slideheight');
	$slideWidth = Mage::getStoreConfig('layerslider/slidesettings/slidewidth');
	$transitionOrder = Mage::getStoreConfig('layerslider/slidesettings/transitionorder');
	
	//Caption Settings of the slide
	$playInMode = Mage::getStoreConfig('layerslider/captionsettings/playinmode');
	$playOutMode = Mage::getStoreConfig('layerslider/captionsettings/playoutmode');
	
	//caption1
	$captionStatus1 = Mage::getStoreConfig('layerslider/captionsettings/caption1');
	$captionDuration1 = Mage::getStoreConfig('layerslider/captionsettings/captionduration1');
	$captionEffect1 = Mage::getStoreConfig('layerslider/captionsettings/captioneffect1');
	
	//caption2
	$captionStatus2 = Mage::getStoreConfig('layerslider/captionsettings/caption2');
	$captionDuration2 = Mage::getStoreConfig('layerslider/captionsettings/captionduration2');
	$captionEffect2 = Mage::getStoreConfig('layerslider/captionsettings/captioneffect2');
	
	//caption3
	$captionStatus3 = Mage::getStoreConfig('layerslider/captionsettings/caption3');
	$captionDuration3 = Mage::getStoreConfig('layerslider/captionsettings/captionduration3');
	$captionEffect3 = Mage::getStoreConfig('layerslider/captionsettings/captioneffect3');
	
	//caption4
	$captionStatus4 = Mage::getStoreConfig('layerslider/captionsettings/caption4');
	$captionDuration4 = Mage::getStoreConfig('layerslider/captionsettings/captionduration4');
	$captionEffect4 = Mage::getStoreConfig('layerslider/captionsettings/captioneffect4');
	
	//caption5
	$captionStatus5 = Mage::getStoreConfig('layerslider/captionsettings/caption5');
	$captionDuration5 = Mage::getStoreConfig('layerslider/captionsettings/captionduration5');
	$captionEffect5 = Mage::getStoreConfig('layerslider/captionsettings/captioneffect5');
	
	//captionimage1
	$captionImg1 = Mage::getStoreConfig('layerslider/captionsettings/captionimg1');
	$captionImgDuration1 = Mage::getStoreConfig('layerslider/captionsettings/captionimgduration1');
	$captionImgEffect1 = Mage::getStoreConfig('layerslider/captionsettings/captionimgeffect1');
	
	//captionimage2
	$captionImg2 = Mage::getStoreConfig('layerslider/captionsettings/captionimg2');
	$captionImgDuration2 = Mage::getStoreConfig('layerslider/captionsettings/captionimgduration2');
	$captionImgEffect2 = Mage::getStoreConfig('layerslider/captionsettings/captionimgeffect2');	
	
?>
<script type="text/javascript">
var $jq = jQuery.noConflict();
	jQuery(document).ready(function()
	{
		    var _SlideshowTransitions = 
			[
				{<?php 
				if($slideEffects!="random")
					echo $slideEffects; 
				else {
					?>
					//Collapse Random
           $Duration: 1000, $Delay: 80, $Cols: 10, $Rows: 4, $Clip: 15, $SlideOut: true, $Easing: $JssorEasing$.$EaseOutQuad }

            //Fade in LR Chess
            , { $Duration: 1200, y: 0.3, $Cols: 2, $During: { $Top: [0.3, 0.7] }, $ChessMode: { $Column: 12 }, $Easing: { $Top: $JssorEasing$.$EaseInCubic, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2, $Outside: true }

            //Rotate VDouble+ out
            , { $Duration: 1000, x: -1, y: 2, $Rows: 2, $Zoom: 11, $Rotate: 1, $SlideOut: true, $Assembly: 2049, $ChessMode: { $Row: 15 }, $Easing: { $Left: $JssorEasing$.$EaseInExpo, $Top: $JssorEasing$.$EaseInExpo, $Zoom: $JssorEasing$.$EaseInExpo, $Opacity: $JssorEasing$.$EaseLinear, $Rotate: $JssorEasing$.$EaseInExpo }, $Opacity: 2, $Round: { $Rotate: 0.85 } }

            ////Swing Inside in Stairs
            , { $Duration: 1200, x: 0.2, y: -0.1, $Delay: 20, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.3, 0.7], $Top: [0.3, 0.7] }, $Formation: $JssorSlideshowFormations$.$FormationStraightStairs, $Assembly: 260, $Easing: { $Left: $JssorEasing$.$EaseInWave, $Top: $JssorEasing$.$EaseInWave, $Clip: $JssorEasing$.$EaseOutQuad }, $Round: { $Left: 1.3, $Top: 2.5} }

            //Zoom HDouble+ out
            , { $Duration: 1200, x: 4, $Cols: 2, $Zoom: 11, $SlideOut: true, $Assembly: 2049, $ChessMode: { $Column: 15 }, $Easing: { $Left: $JssorEasing$.$EaseInExpo, $Zoom: $JssorEasing$.$EaseInExpo, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2 }

            ////Dodge Pet Inside in Stairs
            , { $Duration: 1500, x: 0.2, y: -0.1, $Delay: 20, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.3, 0.7], $Top: [0.3, 0.7] }, $Formation: $JssorSlideshowFormations$.$FormationStraightStairs, $Assembly: 260, $Easing: { $Left: $JssorEasing$.$EaseInWave, $Top: $JssorEasing$.$EaseInWave, $Clip: $JssorEasing$.$EaseOutQuad }, $Round: { $Left: 0.8, $Top: 2.5} }

            //Rotate Zoom+ out BL
            , { $Duration: 1200, x: 4, y: -4, $Zoom: 11, $Rotate: 1, $SlideOut: true, $Easing: { $Left: $JssorEasing$.$EaseInExpo, $Top: $JssorEasing$.$EaseInExpo, $Zoom: $JssorEasing$.$EaseInExpo, $Opacity: $JssorEasing$.$EaseLinear, $Rotate: $JssorEasing$.$EaseInExpo }, $Opacity: 2, $Round: { $Rotate: 0.8 } }

            //Dodge Dance Inside in Random
            , { $Duration: 1500, x: 0.3, y: -0.3, $Delay: 80, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.3, 0.7], $Top: [0.3, 0.7] }, $Easing: { $Left: $JssorEasing$.$EaseInJump, $Top: $JssorEasing$.$EaseInJump, $Clip: $JssorEasing$.$EaseOutQuad }, $Round: { $Left: 0.8, $Top: 2.5 } }

            //Rotate VFork+ out
            , { $Duration: 1200, x: -3, y: 1, $Rows: 2, $Zoom: 11, $Rotate: 1, $SlideOut: true, $Assembly: 2049, $ChessMode: { $Row: 28 }, $Easing: { $Left: $JssorEasing$.$EaseInExpo, $Top: $JssorEasing$.$EaseInExpo, $Zoom: $JssorEasing$.$EaseInExpo, $Opacity: $JssorEasing$.$EaseLinear, $Rotate: $JssorEasing$.$EaseInExpo }, $Opacity: 2, $Round: { $Rotate: 0.7 } }

            //Clip and Chess in
            , { $Duration: 1200, y: -1, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Top: [0.5, 0.5], $Clip: [0, 0.5] }, $Formation: $JssorSlideshowFormations$.$FormationStraight, $ChessMode: { $Column: 12 }, $ScaleClip: 0.5 }

            ////Swing Inside in Swirl
            , { $Duration: 1200, x: 0.2, y: -0.1, $Delay: 20, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.3, 0.7], $Top: [0.3, 0.7] }, $Formation: $JssorSlideshowFormations$.$FormationSwirl, $Assembly: 260, $Easing: { $Left: $JssorEasing$.$EaseInWave, $Top: $JssorEasing$.$EaseInWave, $Clip: $JssorEasing$.$EaseOutQuad }, $Round: { $Left: 1.3, $Top: 2.5} }

            ////Rotate Zoom+ out
            , { $Duration: 1200, $Zoom: 11, $Rotate: 1, $SlideOut: true, $Easing: { $Zoom: $JssorEasing$.$EaseInCubic, $Rotate: $JssorEasing$.$EaseInCubic }, $Opacity: 2, $Round: { $Rotate: 0.7} }

            ////Dodge Pet Inside in ZigZag
            , { $Duration: 1500, x: 0.2, y: -0.1, $Delay: 20, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.3, 0.7], $Top: [0.3, 0.7] }, $Formation: $JssorSlideshowFormations$.$FormationZigZag, $Assembly: 260, $Easing: { $Left: $JssorEasing$.$EaseInWave, $Top: $JssorEasing$.$EaseInWave, $Clip: $JssorEasing$.$EaseOutQuad }, $Round: { $Left: 0.8, $Top: 2.5} }

            //Rotate Zoom- out TL
            , { $Duration: 1200, x: 0.5, y: 0.5, $Zoom: 1, $Rotate: 1, $SlideOut: true, $Easing: { $Left: $JssorEasing$.$EaseInCubic, $Top: $JssorEasing$.$EaseInCubic, $Zoom: $JssorEasing$.$EaseInCubic, $Opacity: $JssorEasing$.$EaseLinear, $Rotate: $JssorEasing$.$EaseInCubic }, $Opacity: 2, $Round: { $Rotate: 0.5 } }

            //Rotate Zoom- in BR
            , { $Duration: 1200, x: -0.6, y: -0.6, $Zoom: 1, $Rotate: 1, $During: { $Left: [0.2, 0.8], $Top: [0.2, 0.8], $Zoom: [0.2, 0.8], $Rotate: [0.2, 0.8] }, $Easing: { $Zoom: $JssorEasing$.$EaseSwing, $Opacity: $JssorEasing$.$EaseLinear, $Rotate: $JssorEasing$.$EaseSwing }, $Opacity: 2, $Round: { $Rotate: 0.5 } }

            // Wave out Eagle
            , { $Duration: 1500, y: -0.5, $Delay: 60, $Cols: 24, $SlideOut: true, $Formation: $JssorSlideshowFormations$.$FormationCircle, $Easing: $JssorEasing$.$EaseInWave, $Round: { $Top: 1.5 } }

            //Expand Stairs
            , { $Duration: 1000, $Delay: 30, $Cols: 10, $Rows: 4, $Clip: 15, $Formation: $JssorSlideshowFormations$.$FormationStraightStairs, $Assembly: 2050, $Easing: $JssorEasing$.$EaseInQuad }

            //Fade Clip out H
            , { $Duration: 1200, $Delay: 20, $Clip: 3, $SlideOut: true, $Assembly: 260, $Easing: { $Clip: $JssorEasing$.$EaseOutCubic, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2 

            ////Dodge Pet Inside in Random Chess
            //, { $Duration: 1500, x: 0.2, y: -0.1, $Delay: 80, $Cols: 10, $Rows: 4, $Clip: 15, $During: { $Left: [0.2, 0.8], $Top: [0.2, 0.8] }, $ChessMode: { $Column: 15, $Row: 15 }, $Easing: { $Left: $JssorEasing$.$EaseInWave, $Top: $JssorEasing$.$EaseInWave, $Clip: $JssorEasing$.$EaseLinear }, $Round: { $Left: 0.8, $Top: 2.5} }
					<?php	
				}
			?>}
			];
			
			var _CaptionTransitions = [];
        
		    // Caption1 
			<?php if($captionStatus1 == 1):?>
			_CaptionTransitions["caption1"] =  {$Duration:<?php echo $captionDuration1 ?>, <?php echo $captionEffect1 ?>};
			<?php endif; ?>
			
			// Caption2
			<?php if($captionStatus2 == 1):?>
			_CaptionTransitions["caption2"] =  {$Duration:<?php echo $captionDuration2 ?>, <?php echo $captionEffect2 ?>};
			<?php endif; ?>
			
			// Caption3
			<?php if($captionStatus3 == 1):?>
			_CaptionTransitions["caption3"] =  {$Duration:<?php echo $captionDuration3 ?>, <?php echo $captionEffect3 ?>};
			<?php endif; ?>
			
			// Caption4
			<?php if($captionStatus4 == 1):?>
			_CaptionTransitions["caption4"] =  {$Duration:<?php echo $captionDuration4 ?>, <?php echo $captionEffect4 ?>};
			<?php endif; ?>
			
			// Caption5
			<?php if($captionStatus5 == 1):?>
			_CaptionTransitions["caption5"] =  {$Duration:<?php echo $captionDuration5 ?>, <?php echo $captionEffect5 ?>};
			<?php endif; ?>
			
			// Caption Image 1
			<?php if($captionImg1 == 1):?>
			_CaptionTransitions["caption-img1"] =  {$Duration:<?php echo $captionImgDuration1 ?>, <?php echo $captionImgEffect1 ?>};
			<?php endif; ?>
			
			// Caption Image 2
			<?php if($captionImg2 == 1):?>
			_CaptionTransitions["caption-img2"] = {$Duration:<?php echo $captionImgDuration2 ?>, <?php echo $captionImgEffect2 ?>};
			<?php endif; ?>
			
            var options = 
			{
				<!--------------------------- SLIDE OPTION ------------------------>
                <!------------- DYNAMIC APPEAR FROM ADMIN START ------------------->
 				$AutoPlay: <?php echo $autoPlay ?>,  //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
				

$AutoPlayInterval: <?php echo $autoPlayInterval ?>,//[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
				$PauseOnHover: <?php echo $pauseOnHover ?>,//[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, default value is 1
				// DYNAMIC PAUSE ON HOVER
                $ArrowKeyNavigation: <?php echo $arrowKeyNav ?>,//[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                //$SlideEasing: $JssorEasing$.$EaseOutQuint,//[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
				$SlideDuration: <?php echo $slideDuration ?>,//[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
				$MinDragOffsetToSlide: <?php echo $minDragOffset ?>,//[Optional] Minimum drag offset to trigger slide , default value is 20
                $DragOrientation:<?php echo $dragOrientation ?>,//[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
			    $PlayOrientation: <?php echo $playOrientation ?>,//[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
				<!------------- DYNAMIC APPEAR FROM ADMIN END ------------------->
				
				
				$AutoPlaySteps: 1,//[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1                
                $SlideSpacing: 0,//[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 1,//[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,//[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,//[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
               
                
                $SlideshowOptions: 
				{   
				
					$Class: $JssorSlideshowRunner$,//[Required] Class to create instance of slideshow
                    $Transitions: _SlideshowTransitions,//[Required] An array of slideshow transitions to play slideshow
                    <!------------- DYNAMIC APPEAR FROM ADMIN START ------------------->
					$TransitionsOrder:<?php echo $transitionOrder ?>,//[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
                    $ShowLink: true //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
					<!------------- DYNAMIC APPEAR FROM ADMIN END ------------------->
                },

                $CaptionSliderOptions: 
				{ 
				    $Class: $JssorCaptionSlider$,//[Required] Class to create instance to animate caption
                    $CaptionTransitions: _CaptionTransitions,//[Required] An array of caption transitions to play caption, see caption transition section at jssor slideshow transition builder
					<!------------- DYNAMIC APPEAR FROM ADMIN START ------------------->
                    $PlayInMode: <?php echo $playInMode ?>,//[Optional] 0 None (no play), 1 Chain (goes after main slide), 3 Chain Flatten (goes after main slide and flatten all caption animations), default value is 1
                    $PlayOutMode: <?php echo $playOutMode ?> //[Optional] 0 None (no play), 1 Chain (goes before main slide), 3 Chain Flatten (goes before main slide and flatten all caption animations), default value is 1
					<!------------- DYNAMIC APPEAR FROM ADMIN END ------------------->
                },

                $ArrowNavigatorOptions: 
				{                      
                    $Class: $JssorArrowNavigator$,
					$Transitions: _SlideshowTransitions, 
					<!------------- DYNAMIC APPEAR FROM ADMIN START ------------------->  
                    $ChanceToShow: <?php echo $arrowNavigation ?>,//[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: <?php echo $arrowAutoCenter ?>,//[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
					<!------------- DYNAMIC APPEAR FROM ADMIN END ------------------->
                    $Steps: 1//[Optional] Steps to go for each navigation request, default value is 1
                },

                $BulletNavigatorOptions: 
				{                         
					$Class: $JssorBulletNavigator$,
					$Transitions: _SlideshowTransitions,   
					<!------------- DYNAMIC APPEAR FROM ADMIN START ------------------->  
                    $ChanceToShow: <?php  echo $bulletNavigation ?>,//[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: <?php echo $bulletAutoCenter ?>, //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
					<!------------- DYNAMIC APPEAR FROM ADMIN END ------------------->  
                    $Steps: 1,//[Optional] Steps to go for each navigation request, default value is 1
                    $Lanes: 1,//[Optional] Specify lanes to arrange items, default value is 1
                    $SpacingX: 4,//[Optional] Horizontal space between each item in pixel, default value is 0
                    $SpacingY: 4,//[Optional] Vertical space between each item in pixel, default value is 0
                    $Orientation: 1//[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
                }
            };
			
			
            var jssor_slider1 = new $JssorSlider$("slider1_container", options);
			function ScaleSlider() 
			{
				var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
    			if (parentWidth)
        			jssor_slider1.$SetScaleWidth(parentWidth);
    			else
        			$JssorUtils$.$Delay(ScaleSlider, 30);
            	}
           		ScaleSlider();
		   		$JssorUtils$.$AddEvent(window, "load", ScaleSlider);
		   		if (!navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|IEMobile)/)) {
    				$JssorUtils$.$OnWindowResize(window, ScaleSlider);
		   		}
         })
	</script>
	