<?php
$buttonSize = $this->getButtonSize();
$buttonPos = $this->getButtonPos();
$footerCol = $this->getBackcolor();

$productName = $this->getProduct ()->getName ();
$productPrice = $this->getProduct ()->getPrice ();

$productPrice = Mage::helper('core')->currency($productPrice,true,false);

$price_des = "Price: " . $productPrice;

$msg = $this->__("Take a look at this awesome product:");
$prd = $this->__($productName);
$bmsg = $this->__("at just");
$display_des = $msg.' '.$prd.' '.$bmsg.' '.$productPrice;

?>
<?php 
if($buttonPos == 2 || $buttonPos == 3)
{
?>
<div id="whats_app_button_footer" style="background-color: <?php echo '#'.$footerCol;?>;
    bottom: 0;
    color: #fff;
    height: 49px;
    padding: 5px 0px;
    position: fixed;
    text-align: center;
    width: 100%;
    display:none;
    ">

<p><?php echo $this->__("Share this link on WhatsApp")?></p>
<div>
<a href="whatsapp://send" data-text='<?php echo $display_des;?>'
	data-href="" class="wa_btn wa_btn_<?php echo $buttonSize?>" style="display:none;"><?php echo $this->__("Share")?></a>
</div>
</div>
<?php }?>